---
layout: post
title: "Python: 예외처리(try, except, finally)"
date: 2024-11-20
categories: [Python] 
---

#### 1. 에러와 예외의 차이
- **에러(Error)**

프로그램이 실행 중에 발생하는 문제로, 종종 프로그램이 비정상적으로 종료되게 만듭니다. 예를 들어, 파일을 열려고 하는데 해당 파일이 없거나, 숫자를 0으로 나누는 경우 에러가 발생할 수 있습니다.

- **예외(Exception)**

에러의 한 종류로, 예외가 발생하면 프로그램이 멈추고 에러 메시지를 출력합니다. 하지만 예외는 **예외 처리**를 통해 프로그램이 멈추지 않고, 에러를 처리하며 계속 실행되게 할 수 있습니다.

**에러가 발생하는 예시**

```python
# 예시 1: 0으로 나누기
print(10 / 0)  # ZeroDivisionError

# 예시 2: 없는 파일 열기
file = open("없는파일.txt", "r")  # FileNotFoundError

# 예시 3: 잘못된 인덱스 접근
numbers = [1, 2, 3]
print(numbers[5])  # IndexError
```

#### 2. try, except 예외 처리의 기본 구조
**예외 처리의 기본 구조**
Python에서 예외를 처리하기 위해 **`try`**와 **`except`** 블록을 사용합니다.
**`try`** 블록 안에 예외가 발생할 가능성이 있는 코드를 작성하고, 
**`except`** 블록에서 그 예외를 처리합니다.

```python
try:
    # 예외가 발생할 가능성이 있는 코드
except 예외타입:
    # 예외가 발생했을 때 실행할 코드
```
기본 구조 예시

```python
# try 블록의 코드가 실행되다가 ZeroDivisionError 예외가 발생하면, except 블록의 코드가 실행되어 "0으로 나눌 수 없습니다!"라는 메시지를 출력
try:
    print(10 / 0)
except ZeroDivisionError:
    print("0으로 나눌 수 없습니다!")
```

**여러 예외 처리**
하나의 `try` 블록에서 여러 개의 `except` 블록을 사용하여, 다양한 예외를 처리할 수 있습니다.

예외 처리 예시

```python
# ValueError와 ZeroDivisionError 예외를 각각 처리하여, 사용자가 잘못된 입력을 하거나 0을 입력했을 때 적절한 메시지를 출력
try:
    x = int(input("숫자를 입력하세요: "))
    result = 10 / x
except ValueError:
    print("유효한 숫자가 아닙니다.")
except ZeroDivisionError:
    print("0으로 나눌 수 없습니다.")
```

**모든 예외 처리**
특정 예외를 지정하지 않고, 모든 예외를 처리할 수도 있습니다.

```python
# 어떤 예외가 발생하든, "예외가 발생했습니다." 메시지 출력
try:
    print(10 / 0)
except:
    print("예외가 발생했습니다.")
```

#### 3. finally 항상 실행되는 코드 블록

**finally 블록을 이용한 예외 처리의 기본 구조**
**`finally`** 블록은 예외 발생 여부에 상관없이 **항상 실행되는 코드 블록**입니다.
주로 **리소스 정리**(예: 파일 닫기, 네트워크 연결 종료 등)와 같은 작업을 수행할 때 사용됩니다.

```python
try:
    # 예외가 발생할 가능성이 있는 코드
except 예외타입:
    # 예외가 발생했을 때 실행할 코드
finally:
    # 예외 발생 여부와 상관없이 항상 실행할 코드
```

finally 블록 이용한 예외 처리 예시

```python
# 파일이 존재하지 않더라도, `finally` 블록이 실행되어 파일을 닫고 "파일을 닫았습니다." 메시지를 출력
file = None
try:
    file = open("data.txt", "r")
    data = file.read()
except FileNotFoundError:
    print("파일을 찾을 수 없습니다.")
finally:
    if file is not None:
        file.close()
    print("파일을 닫았습니다.")
```
**예외가 발생하지 않아도 실행**
`finally` 블록은 예외가 발생하지 않더라도 실행됩니다.

```python
# 예외가 발생하지 않지만, `finally` 블록이 실행되어 "프로그램 종료."라는 메시지 출력
try:
    result = 10 / 2
    print(result)
except ZeroDivisionError:
    print("0으로 나눌 수 없습니다.")
finally:
    print("프로그램 종료.")
```
